# goreleaser.yml
project_name: links
build:
  binary: links
  goos:
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
nfpms:
  - homepage: https://github.com/lrstanley/links
    maintainer: Liam Stanley <me@liamstanley.io>
    description: Links -- Link shortening service.
    license: MIT
    formats:
      - deb
      - rpm
archives:
  - id: tgz
    format: tar.gz
  - id: windows
    goos: windows
    format: zip
release:
  draft: true
snapshot:
  name_template: snapshot-{{.Commit}}
