# goreleaser.yml
build:
  binary: links
  goos:
    - windows
    - linux
    - freebsd
  goarch:
    - amd64
    - 386
archive:
  format_overrides:
    - goos: windows
      format: zip
release:
  draft: true
snapshot:
  name_template: snapshot-{{.Commit}}
