# goreleaser.yml
project_name: links
build:
  binary: links
  goos:
    - linux
    - freebsd
  goarch:
    - amd64
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  hooks:
    post: make compress
nfpm:
  homepage: https://github.com/lrstanley/links
  maintainer: Liam Stanley <me@liamstanley.io>
  description: Links -- Link shortening service.
  license: MIT
  formats:
    - deb
    - rpm
archive:
  format: tar.gz
release:
  draft: true
snapshot:
  name_template: snapshot-{{.Commit}}
