language: go
go:
- 1.13.x
- tip
script:
- make build
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.byteirc.org#/dev/null
    template:
    - "%{repository} #%{build_number} %{branch}/%{commit}: %{author} -- %{message}
      %{build_url}"
    on_success: change
    on_failure: change
