# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: docker-master

on:
  push:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: publish image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: lrstanley/links
        tags: master
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}